-- Migration: Adicionar colunas de auditoria nas tabelas existentes
-- Versão: 002
-- Data: 2024-04-28

-- Adicionar colunas de auditoria na tabela de clientes
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) DEFAULT 'SISTEMA' NOT NULL;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) DEFAULT 'SISTEMA' NOT NULL;

-- Adicionar colunas de auditoria na tabela de produtos
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) DEFAULT 'SISTEMA' NOT NULL;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) DEFAULT 'SISTEMA' NOT NULL;

-- Adicionar colunas de auditoria na tabela de usuários
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) DEFAULT 'SISTEMA' NOT NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) DEFAULT 'SISTEMA' NOT NULL;

